---
- name: set_facts | Setting Shorewall Version
  set_fact:
    shorewall_version: 4
  when: >
    ansible_distribution == "Debian" and ansible_distribution_version|int < 9

- name: set_facts | Setting Shorewall Version
  set_fact:
    shorewall_version: 5
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '16.04') or
    (ansible_distribution == 'CentOS' and ansible_distribution_version >= '7.0')

- name: set_facts | Setting Shorewall Default Actions/Macros
  set_fact:
    shorewall_default_actions_macros: legacy
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int < 10) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version < '18.04')

- name: set_facts | Setting Shorewall Default Actions/Macros
  set_fact:
    shorewall_default_actions_macros: new
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int > 9) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '18.04') or
    (ansible_distribution == 'CentOS' and ansible_distribution_version >= '7.0')

- name: get docker network id
  shell: "docker network ls | grep {{ env }}_default | awk '{ print $1 }'"
  register: docker_network_id
  changed_when: false
  failed_when: false

