---
# handlers file for ansible-shorewall
# when restarting shorewall, first validate the config!
- name: restart shorewall
  shell: shorewall check
  become: true
  notify: restart shorewall after check
  tags:
    - skip_ansible_lint

- name: restart shorewall after check
  service:
    name: shorewall
    state: restarted
  become: true
  notify: restart docker daemon required

# WORKAROUND: When (re)starting shorewall, the DOCKER related chains are corrupted. Set this flag here, and check in
#             the dh.docker role to actually restart the daemon
- name: restart docker daemon required
  set_fact:
    restart_docker_daemon_required: true
